// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrpevihxkuqwdbvcdmqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhycGV2aWh4a3Vxd2RidmNkbXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDAwMDksImV4cCI6MjA2MTQxNjAwOX0.PDlLN_SE-sJy_sZ3u0H9Oe1RiJ-iSMo5Zl0AMJIit1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);